package com.example.perpustakaanapplication

object BookData {
    val listBook = arrayListOf<Book>(
        Book("A House Divided", "Nicole Ciacchella", "Novel", "English", 226, "Cianne Wyland leads a double life. No one in House Staerleigh would suspect that the meek woman on whom they heap their disdain is a gatherer of secrets. Determined to uncover whether the House's upper echelon—including her own father—are engaging in illicit activities in a grasp for control of the House, Cianne has made an art of slipping into their homes to rifle through their private lives. Kila an Movis is an Enforcer. Gods-gifted with an extraordinary ability to piece together physical clues, he's entrusted with protecting the vulnerable from crime. But his habit of expressing his opinions a little too freely earned him a nine-year banishment to the wilds, and he's determined to be more circumspect upon his return to the trade city. When someone close to Cianne dies and Kila is called out to investigate the scene, her world and his collide once more. His long absence hasn't driven the memory of him from her heart, but the woman he encounters isn't the child he remembers. Unwilling to trust anyone else, Cianne enlists Kila's help. The deeper they dig, the more secrets they unearth about her father, the other House members, and her entire life—until Cianne discovers that House Staerleigh is built on a foundation of lies.", R.drawable.a_house_divided, "a_house_divided.pdf"),
        Book("Around the World in Eighty Days", "Jules Verne", "Novel", "English", 201, "The Project Gutenberg EBook of Around the World in 80 Days, by Jules Verne", R.drawable.around_the_world_in_eighty_days, "around_the_world_in_eighty_days.pdf"),
        Book("Skylar Robbins: The Mystery of the Hidden Jewels", "Carrie Cross", "Novel", "English", 165, "Skylar Robbins: The Mystery of the Hidden Jewels  by Carrie Cross", R.drawable.skylar_robbins_the_mystery_of_the_hidden_jewels, "skylar_robbins_the_mystery_of_the_hidden_jewels.pdf"),
        Book("The Adventures of Huckleberry Finn (Tom Sawyer's Comrade)", "Mark Twain", "Novel", "English", 306, "Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain", R.drawable.the_adventures_of_huckleberry_finn_tom_sawyers_comrade, "the_adventures_of_huckleberry_finn_tom_sawyer's_comrade.pdf"),
        Book("White Fang", "Jack London", "Novel", "English", 178, "The Project Gutenberg eBook, White Fang, by Jack London", R.drawable.white_fang, "white_fang.pdf"),
        Book("Robinson Crusoe", "Daniel Defoe", "Novel", "Finnish", 143, "The Project Gutenberg EBook of Robinson Crusoe, by Daniel Defoe", R.drawable.robinson_crusoe, "robinson_crusoe.pdf"),
        Book("20000 Lieues sous les mers", "Jules Verne", "Novel", "French", 449, "The Project Gutenberg EBook of 20000 Lieues sous les mers Parts 1&2 by Jules Verne", R.drawable._20000_lieues_sous_les_mers, "20000_lieues_sous_les_mers.pdf"),
        Book("Dead & Buried (A Partners in Crime Supernatural Mystery)", "T.K. Eldridge", "Novel", "English", 186, "Being ignored or shunned was not something they were used to. Doting parents, sycophant friends, they all hung on their every word. The best schools, the best clothes, the best trainers, no expense had been spared. When someone grows up with every wish granted, every desire fulfilled, what more could they strive towards? Oh, they knew they should be grateful. Charitable, even. Instead, they had decided that it was time to take the next step. No more being under parental control, no more answering to every demand of mother or father – it was time to show them just what they’d created. Thumbs danced across the screen, and the text was sent. A reply came back moments later. “Target acquired. One by one, they’d all come tumbling down. It was only fair. What else was a person supposed to do for family, if not take up their battles when they could no longer fight?", R.drawable.dead_and_buried_a_partners_in_crime_supernatural_mystery, "dead_&_buried_a_partners_in_crime_supernatural_mystery.pdf"),
        Book("A Princess of Mars", "Edgar Rice Burroughs", "Novel", "English", 177, "The Project Gutenberg EBook of A Princess of Mars, by Edgar Rice Burroughs", R.drawable.a_princess_of_mars, "a_princess_of_mars.pdf"),
        Book("The Thirty-Nine Steps", "John Buchan", "Novel", "English", 103, "The Project Gutenberg EBook of The Thirty-nine Steps, by John Buchan", R.drawable.the_thirty_nine_steps, "the_thirty-nine_steps.pdf")
    )
}